dietplan/config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :homes
  resources :snacks
  resources :drinks
  resources :meats
  resources :fruits
  resources :normals
  resources :needamounts
  resources :bmicalculates
  resources :twentyones
  resources :eggdiets
  resources :thirteens
  resources :threes
  resources :sevens
  resources :women
  resources :men
  resources :needs
  resources :bmitables
  resources :calculates
  resources :foods
  
  root 'homes#index'
end

dietplan/app/models/about.rb
class About < ApplicationRecord
end

dietplan/app/models/bmicalculate.rb
class Bmicalculate < ApplicationRecord
    validates :weight, :height, presence: true
end

dietplan/app/models/bmitable.rb
class Bmitable < ApplicationRecord
end

dietplan/app/models/eggdiet.rb
class Eggdiet < ApplicationRecord
end

dietplan/app/models/food.rb
class Food < ApplicationRecord
  
    validates :name, :calorie, :protein, :carbohydrate, :fat, :image, presence: true
    has_one_attached :image  
                    
end

dietplan/app/models/fruit.rb
class Fruit < ApplicationRecord
end

dietplan/app/models/home.rb
class Home < ApplicationRecord
end

dietplan/app/models/man.rb
class Man < ApplicationRecord
end

dietplan/app/models/meat.rb
class Meat < ApplicationRecord
end

dietplan/app/models/normal.rb
class Normal < ApplicationRecord
    validates :weight, :height, :age, presence: true
end

dietplan/app/models/seven.rb
class Seven < ApplicationRecord
end

dietplan/app/models/snack.rb
class Snack < ApplicationRecord
end

dietplan/app/models/thirteen.rb
class Thirteen < ApplicationRecord
end

dietplan/app/models/three.rb
class Three < ApplicationRecord
end

dietplan/app/models/twentyone.rb
class Twentyone < ApplicationRecord
end

dietplan/app/models/woman.rb
class Woman < ApplicationRecord
end

dietplan/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name)
    end
end

dietplan/app/helpers/foods_helper.rb
module FoodsHelper
end

dietplan/app/helpers/homes_helper.rb
module HomesHelper
end

dietplan/app/helpers/meats_helper.rb
module MeatsHelper
end

dietplan/app/helpers/men_helper.rb
module MenHelper
end

dietplan/app/helpers/needs_helper.rb
module NeedsHelper
end

dietplan/app/helpers/women_helper.rb
module WomenHelper
end

dietplan/app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

dietplan/app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

dietplan/app/views/homes/index.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">

<!-- Indicators -->
<ol class="carousel-indicators">
  <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
  <li data-target="#myCarousel" data-slide-to="1" class=""></li>
</ol>

<!-- Wrapper for slides -->
<div class="carousel-inner" role="listbox">

  <div class="item active">
    <%= image_tag "diet.jpg" %>             
  </div><!--- End Active-->

  <div class="item">
    <%= image_tag "diet3.jpg"  %>           
  </div>

</div>

<!--- Start Slider Controls-->
<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
  <span class="sr-only">Previous</span>
</a>

<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
  <span class="sr-only">Next</span>
</a>

</div> <!--- End Slider -->

<div class="container text-center">    
  <h3><b>What are  calories, proteins, carbohydrates and fats?</b></h3><br>
</div>


  <div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h4><i>Calories</i></h4>
      <p>Calories in food provide energy in the form of heat so that our bodies can function. Our bodies store and "burn" calories as fuel. Many dieters count calories and try to decrease caloric intake to lose weight.
      Different types of food provide different levels of energy. 
      </p>
    </div>  

    <div class="col-sm-6">
      <h4><i>Proteins</i></h4>          
      <p>
      The human body uses proteins for many things, including repairing and building tissues, acting as enzymes, aiding the immune system, and serving as hormones. Each of these important functions requires a slightly different form of protein. 
      </p>
    </div>

  </div>
  </div>

  <div class="container">
  <div class="row">

  <div class="col-sm-6">
    <h4><i>Carbohydrates</i></h4>
    <p>Carbohydrates are the sugars, starches and fibers found in fruits, grains, vegetables and milk products. Though often maligned in trendy diets, carbohydrates — one of the basic food groups — are important to a healthy life.
    They are a major food source and a key form of energy for most organisms.
    </p>
  </div>

  <div class="col-sm-6"> 
   <h4><i>Fats</i></h4>         
   <p>Fat is an essential part of our diet and nutrition, and we cannot live without it.
   Our bodies require small amounts of 'good fat' to function and help prevent disease.
   However, a lot of modern diets contain far more fat than the body needs.   
   </p>
  </div>

</div>

</div>

dietplan/app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

dietplan/app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>