dietplan/config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :homes
  resources :snacks
  resources :drinks
  resources :meats
  resources :fruits
  resources :normals
  resources :needamounts
  resources :bmicalculates
  resources :twentyones
  resources :eggdiets
  resources :thirteens
  resources :threes
  resources :sevens
  resources :women
  resources :men
  resources :needs
  resources :bmitables
  resources :calculates
  resources :foods
  
  root 'homes#index'
end

dietplan/app/models/about.rb
class About < ApplicationRecord
end

dietplan/app/models/bmicalculate.rb
class Bmicalculate < ApplicationRecord
    validates :weight, :height, presence: true
end

dietplan/app/models/bmitable.rb
class Bmitable < ApplicationRecord
end

dietplan/app/models/eggdiet.rb
class Eggdiet < ApplicationRecord
end

dietplan/app/models/food.rb
class Food < ApplicationRecord
  
    validates :name, :calorie, :protein, :carbohydrate, :fat, :image, presence: true
    has_one_attached :image  
                    
end

dietplan/app/models/fruit.rb
class Fruit < ApplicationRecord
end

dietplan/app/models/home.rb
class Home < ApplicationRecord
end

dietplan/app/models/man.rb
class Man < ApplicationRecord
end

dietplan/app/models/meat.rb
class Meat < ApplicationRecord
end

dietplan/app/models/normal.rb
class Normal < ApplicationRecord
    validates :weight, :height, :age, presence: true
end

dietplan/app/models/seven.rb
class Seven < ApplicationRecord
end

dietplan/app/models/snack.rb
class Snack < ApplicationRecord
end

dietplan/app/models/thirteen.rb
class Thirteen < ApplicationRecord
end

dietplan/app/models/three.rb
class Three < ApplicationRecord
end

dietplan/app/models/twentyone.rb
class Twentyone < ApplicationRecord
end

dietplan/app/models/woman.rb
class Woman < ApplicationRecord
end

dietplan/app/controllers/normals_controller.rb
class NormalsController < ApplicationController
  before_action :set_normal, only: [:show, :edit, :update, :destroy]

  # GET /normals
  # GET /normals.json
  def index
    @normals = Normal.all
  end

  # GET /normals/1
  # GET /normals/1.json
  def show
  end

  # GET /normals/new
  def new
    @normal = Normal.new
  end

  # GET /normals/1/edit
  def edit
  end

  # POST /normals
  # POST /normals.json
  def create
    @normal = Normal.new(normal_params)

    respond_to do |format|

      if (@normal.present? && @normal.height.present? && @normal.weight.present? && @normal.age.present?)       
        if params["theme"] == "male"
          @normal.total = 10* @normal.weight + 6.25 * @normal.height - 5 * @normal.age + 5
        elsif params["theme"] == "female"
          @normal.total = 10* @normal.weight + 6.25 * @normal.height - 5 * @normal.age - 161        
        else
          @error = "Need to choose gender"
        end
      else
        @error = "Need to fill weight, height, and age"
    end

    if @error.present?
      format.html { render :new }   
      format.json { render json: @normal.errors, status: :unprocessable_entity }
  else

      if @normal.save
        format.html { redirect_to @normal, notice: 'Normal was successfully created.' }
        format.json { render :show, status: :created, location: @normal }
      else
        format.html { render :new }
        format.json { render json: @normal.errors, status: :unprocessable_entity }
      end
    end
  end
end

  # PATCH/PUT /normals/1
  # PATCH/PUT /normals/1.json
  def update
    respond_to do |format|
      if @normal.update(normal_params)
        format.html { redirect_to @normal, notice: 'Normal was successfully updated.' }
        format.json { render :show, status: :ok, location: @normal }
      else
        format.html { render :edit }
        format.json { render json: @normal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /normals/1
  # DELETE /normals/1.json
  def destroy
    @normal.destroy
    respond_to do |format|
      format.html { redirect_to normals_url, notice: 'Normal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_normal
      @normal = Normal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def normal_params
      params.require(:normal).permit(:weight, :height, :age, :total)
    end
end

dietplan/app/helpers/foods_helper.rb
module FoodsHelper
end

dietplan/app/helpers/homes_helper.rb
module HomesHelper
end

dietplan/app/helpers/meats_helper.rb
module MeatsHelper
end

dietplan/app/helpers/men_helper.rb
module MenHelper
end

dietplan/app/helpers/needs_helper.rb
module NeedsHelper
end

dietplan/app/helpers/normals_helper.rb
module NormalsHelper
end

dietplan/app/views/normals/_form.html.erb
<%= form_for @normal, :html => { :class => "form-horizontal normal" } do |f| %>

  <% if @normal.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@normal.errors.count, "error") %> prohibited this normal from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @normal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="container">

  <div class="form-group">
    <%= f.label :weight, 'Weight ( lb )', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :weight, :class => 'form-control' %>
    </div>
    <%=f.error_span(:weight) %>
  </div>
  <div class="form-group">
    <%= f.label :height, 'Height ( inches )' , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :height, :class => 'form-control' %>
    </div>
    <%=f.error_span(:height) %>
  </div>
  <div class="form-group">
    <%= f.label :age, 'Age ( years )' , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%=f.error_span(:age) %>
  </div>
  
  <div class="container text-center">
  <div class="form-group">    
    <div class="col-lg-10">
       <div class="form_row">
         <%= radio_button_tag 'theme', "male", @theme == "male" %><b>Male</b>
         <%= radio_button_tag 'theme', "female", @theme == "female" %><b>Female</b>
       </div>
    </div>
    <%=f.error_span(:theme) %>
  </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>

  </div>

<% end %>

dietplan/app/views/normals/edit.html.erb
<%- model_class = Normal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

dietplan/app/views/normals/index.html.erb
<%- model_class = Normal -%>

<div class="container">

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:height) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:total) %></th>
     
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @normals.each do |normal| %>
      <tr>
        
        <td><%= normal.weight %></td>
        <td><%= normal.height %></td>
        <td><%= normal.age %></td>
        <td><%= normal.total %></td>
        
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      normal_path(normal), :class => 'btn btn-default btn-xs' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_normal_path,
            :class => 'btn btn-primary' %>

</div>

dietplan/app/views/normals/new.html.erb
<div class="container">
  <div class="row"> 
      <%= image_tag("needcalorie.jpg", :width => "100%", :height => "100%") %>     
  </div>  
</div> 

<%- model_class = Normal -%>

<div class="container">

<div class="page-header">
  <h3><i>Normal needed calorie for you</i></h3>
</div>
<%= render :partial => 'form' %>

</div>

<div class="container">
     <%= link_to ' Average Needed Calorie for man', men_path %> |
     <%= link_to ' Average Needed Calorie for woman', women_path %>
</div>

dietplan/app/views/normals/show.html.erb
<%- model_class = Normal -%>

<div class="container">

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @normal.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:height) %>:</strong></dt>
  <dd><%= @normal.height %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @normal.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total) %>:</strong></dt>
  <dd><%= @normal.total %></dd>
  
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              new_normal_path, :class => 'btn btn-default'  %>

</div>