dietplan/config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :homes
  resources :snacks
  resources :drinks
  resources :meats
  resources :fruits
  resources :normals
  resources :needamounts
  resources :bmicalculates
  resources :twentyones
  resources :eggdiets
  resources :thirteens
  resources :threes
  resources :sevens
  resources :women
  resources :men
  resources :needs
  resources :bmitables
  resources :calculates
  resources :foods
  
  root 'homes#index'
end

dietplan/app/models/about.rb
class About < ApplicationRecord
end

dietplan/app/models/bmicalculate.rb
class Bmicalculate < ApplicationRecord
    validates :weight, :height, presence: true
end

dietplan/app/models/bmitable.rb
class Bmitable < ApplicationRecord
end

dietplan/app/models/eggdiet.rb
class Eggdiet < ApplicationRecord
end

dietplan/app/models/food.rb
class Food < ApplicationRecord
  
    validates :name, :calorie, :protein, :carbohydrate, :fat, :image, presence: true
    has_one_attached :image  
                    
end

dietplan/app/models/fruit.rb
class Fruit < ApplicationRecord
end

dietplan/app/models/home.rb
class Home < ApplicationRecord
end

dietplan/app/models/man.rb
class Man < ApplicationRecord
end

dietplan/app/models/meat.rb
class Meat < ApplicationRecord
end

dietplan/app/models/normal.rb
class Normal < ApplicationRecord
    validates :weight, :height, :age, presence: true
end

dietplan/app/models/seven.rb
class Seven < ApplicationRecord
end

dietplan/app/models/snack.rb
class Snack < ApplicationRecord
end

dietplan/app/models/thirteen.rb
class Thirteen < ApplicationRecord
end

dietplan/app/models/three.rb
class Three < ApplicationRecord
end

dietplan/app/models/twentyone.rb
class Twentyone < ApplicationRecord
end

dietplan/app/models/woman.rb
class Woman < ApplicationRecord
end

dietplan/app/controllers/threes_controller.rb
class ThreesController < ApplicationController
  before_action :set_three, only: [:show, :edit, :update, :destroy]

  # GET /threes
  # GET /threes.json
  def index
    @threes = Three.all
  end

  # GET /threes/1
  # GET /threes/1.json
  def show
  end

  # GET /threes/new
  def new
    @three = Three.new
  end

  # GET /threes/1/edit
  def edit
  end

  # POST /threes
  # POST /threes.json
  def create
    @three = Three.new(three_params)

    respond_to do |format|
      if @three.save
        format.html { redirect_to @three, notice: 'Three was successfully created.' }
        format.json { render :show, status: :created, location: @three }
      else
        format.html { render :new }
        format.json { render json: @three.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /threes/1
  # PATCH/PUT /threes/1.json
  def update
    respond_to do |format|
      if @three.update(three_params)
        format.html { redirect_to @three, notice: 'Three was successfully updated.' }
        format.json { render :show, status: :ok, location: @three }
      else
        format.html { render :edit }
        format.json { render json: @three.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /threes/1
  # DELETE /threes/1.json
  def destroy
    @three.destroy
    respond_to do |format|
      format.html { redirect_to threes_url, notice: 'Three was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_three
      @three = Three.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def three_params
      params.require(:three).permit(:day, :breakfast, :lunch, :dinner)
    end
end

dietplan/app/helpers/foods_helper.rb
module FoodsHelper
end

dietplan/app/helpers/homes_helper.rb
module HomesHelper
end

dietplan/app/helpers/meats_helper.rb
module MeatsHelper
end

dietplan/app/helpers/men_helper.rb
module MenHelper
end

dietplan/app/helpers/needs_helper.rb
module NeedsHelper
end

dietplan/app/helpers/threes_helper.rb
module ThreesHelper
end

dietplan/app/views/threes/_form.html.erb
<%= form_for @three, :html => { :class => "form-horizontal three" } do |f| %>

  <% if @three.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@three.errors.count, "error") %> prohibited this three from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @three.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="container">

  <div class="form-group">
    <%= f.label :day, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :day, :class => 'form-control' %>
    </div>
    <%=f.error_span(:day) %>
  </div>
  <div class="form-group">
    <%= f.label :breakfast, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :breakfast, :class => 'form-control' %>
    </div>
    <%=f.error_span(:breakfast) %>
  </div>
  <div class="form-group">
    <%= f.label :lunch, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lunch, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lunch) %>
  </div>
  <div class="form-group">
    <%= f.label :dinner, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :dinner, :class => 'form-control' %>
    </div>
    <%=f.error_span(:dinner) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                threes_path, :class => 'btn btn-default' %>
    </div>
  </div>

  </div>

<% end %>

dietplan/app/views/threes/edit.html.erb
<%- model_class = Three -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

dietplan/app/views/threes/index.html.erb
<div class="container">
    <%= link_to ' * Seven Days Diet Plan', sevens_path %><br>
    <%= link_to ' * Boiled Eggs Diet Plan', eggdiets_path %><br>
    <%= link_to ' * Thirteen Days Diet Plan', thirteens_path %><br>
    <%= link_to ' * Twenty-one Days Diet Plan', twentyones_path %><br>
</div>

<div class="container">

<%- model_class = Three -%>

<div class="page-header">
<h3><i>Three Days Diet Plan ( Lose 10 pounds )</i></h3>
</div>

<table class="table table-striped">

  <thead>
    <tr>      
      <th><%= model_class.human_attribute_name(:day) %></th>
      <th><%= model_class.human_attribute_name(:breakfast) %></th>
      <th><%= model_class.human_attribute_name(:lunch) %></th>
      <th><%= model_class.human_attribute_name(:dinner) %></th>      
    </tr>
  </thead>

  <tbody>
    <% @threes.each do |three| %>
      <tr>        
        <td><%= three.day %></td>
        <td><%= three.breakfast %></td>
        <td><%= three.lunch %></td>
        <td><%= three.dinner %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      three_path(three), :class => 'btn btn-default btn-xs' %>
          
        </td>      
      </tr>
    <% end %>
  </tbody>
  
  </table>

  </div>

  <div class="container">
      <strong>Things to remember</strong><br>
         <p>
            <strong>
              * You must avoid pasta, salty food, sugar, fast food, fried food. (eg. potatoes chip, readymade food,.. etc)<br>
              * You must remark your weight before diet, and compare after diet.
            </strong>
         </p> 
  </div>

dietplan/app/views/threes/new.html.erb
<%- model_class = Three -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

dietplan/app/views/threes/show.html.erb
<div class="container">

<%- model_class = Three -%>
<div class="page-header">
<h3><i>Three Days Diet Plan </i></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:day) %>:</strong></dt>
  <dd><%= @three.day %></dd>
  <dt><strong><%= model_class.human_attribute_name(:breakfast) %>:</strong></dt>
  <dd><%= @three.breakfast %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lunch) %>:</strong></dt>
  <dd><%= @three.lunch %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dinner) %>:</strong></dt>
  <dd><%= @three.dinner %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              threes_path, :class => 'btn btn-default'  %>


</div>