dietplan/config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :homes
  resources :snacks
  resources :drinks
  resources :meats
  resources :fruits
  resources :normals
  resources :needamounts
  resources :bmicalculates
  resources :twentyones
  resources :eggdiets
  resources :thirteens
  resources :threes
  resources :sevens
  resources :women
  resources :men
  resources :needs
  resources :bmitables
  resources :calculates
  resources :foods
  
  root 'homes#index'
end

dietplan/app/models/about.rb
class About < ApplicationRecord
end

dietplan/app/models/bmicalculate.rb
class Bmicalculate < ApplicationRecord
    validates :weight, :height, presence: true
end

dietplan/app/models/bmitable.rb
class Bmitable < ApplicationRecord
end

dietplan/app/models/eggdiet.rb
class Eggdiet < ApplicationRecord
end

dietplan/app/models/food.rb
class Food < ApplicationRecord
  
    validates :name, :calorie, :protein, :carbohydrate, :fat, :image, presence: true
    has_one_attached :image  
                    
end

dietplan/app/models/fruit.rb
class Fruit < ApplicationRecord
end

dietplan/app/models/home.rb
class Home < ApplicationRecord
end

dietplan/app/models/man.rb
class Man < ApplicationRecord
end

dietplan/app/models/meat.rb
class Meat < ApplicationRecord
end

dietplan/app/models/normal.rb
class Normal < ApplicationRecord
    validates :weight, :height, :age, presence: true
end

dietplan/app/models/seven.rb
class Seven < ApplicationRecord
end

dietplan/app/models/snack.rb
class Snack < ApplicationRecord
end

dietplan/app/models/thirteen.rb
class Thirteen < ApplicationRecord
end

dietplan/app/models/three.rb
class Three < ApplicationRecord
end

dietplan/app/models/twentyone.rb
class Twentyone < ApplicationRecord
end

dietplan/app/models/woman.rb
class Woman < ApplicationRecord
end

dietplan/app/helpers/foods_helper.rb
module FoodsHelper
end

dietplan/app/helpers/homes_helper.rb
module HomesHelper
end

dietplan/app/helpers/meats_helper.rb
module MeatsHelper
end

dietplan/app/helpers/men_helper.rb
module MenHelper
end

dietplan/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>  
        <span class="icon-bar"></span>                  
      </button>

      <a class="navbar-brand" href="#"><img src = "">Healthy Diet</a>

    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
    
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><li><%=link_to "Home", homes_path%></li></li>
        <li><%=link_to "BMI", new_bmicalculate_path%></li>
        <li><%=link_to "Needed Calorie", new_normal_path%></li>
        <li><%=link_to "Diet Plan", threes_path%></li>
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Categories<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%=link_to "Vegetables,Fruits", fruits_path%></li>
                <li><%=link_to "Meat,Seafood", meats_path%></li>
                <li><%=link_to "Drinks,Fast food", snacks_path%></li>
                <li class="divider"></li>
                <li><%=link_to "Other Recipes", foods_path%></li>
              </ul>
        </li>
            
      </ul>

    </div>
  </div>
</nav>

dietplan/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dietplan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>

  .navbar {
    margin-bottom: 0;
    border-radius: 0;
    background-color: rgb(20, 18, 20);
    color: #FFF;
    padding: 1% 0;
    font-size: 1.2em;
    border: 0;
  }
    
    .carousel-inner img {
      width: 100%; 
      margin: auto;
      min-height:150px;
  }

  @media (max-width: 600px) {
    .carousel-caption {
      display: none; 
    }
  }
  }

  </style>

  <body>

     <%= render 'layouts/navigation' %>

    <%= yield %>

  </body>
</html>